name: offline_ride_tracker
description: "A basic Flutter project called Offline Ride Tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.0.2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/route_data.json
